# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4243450698b5a51c02eb3a64b818d3a53352c8e5243b1851b8d9e1135e434f1e42caf12107df8335c1136c5fdff0031b7648dce7f0b306a70ef03ec96b0e2e62

test:
  secret_key_base: b85c550bb87ef8935fa6dfb186f2265be6292259a737ca3cf00b08b964086a9766914a43d2b885013ff83fecef5ac682b6e9a68e91d6494a4dbdda0c05405c73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
